language: php

php:
  - 5.3
  - 5.4
  
env:
 - WP_VERSION=master WP_MULTISITE=1
 - WP_VERSION=3.2.1 WP_MULTISITE=1

# Grab the setup script and execute
before_script:
    - wget https://raw.github.com/benbalter/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh

script: phpunit
